### ISSUE TITLE
Select, deselect, re-select place produces multiple 'read me' links

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/BreezeMap#10]
Select a category.
Click a list item. A read me link shows at the bottom of the div.
De-select the item. The read me link disappears.
Re-select the (same) item. Two read me links appear.
Continue clicking the list item. New read me link for each click.
The same behaviour occurs if a polygon on the map is clicked multiple times.
Expected behaviour: de-selecting item and re-selecting should only produce one read me no matter how many time sit is selected/de-selected/re-selected.

**Comment by martindholmes** [comment]
That's actually intentional. The idea is that you didn't deselect the item; you just hid the menu.

**Comment by martindholmes** [comment]
Fixed in commit 89e0cb2.
