### ISSUE TITLE
"Read more..." link does not change linked document

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/BreezeMap#12]
Once a document has been loaded in the sidebar (left) viewing other linked documents (local and remote) is impossible. That is, clicking the "Read more..." link on subsequent 'selected' locations does not load the linked document. The previous page seems to reload.
Tested on fresh checkout on campus map.

**Comment by martindholmes** [comment]
Confirmed. May be a result of the last bugfix I did. :-(

**Comment by martindholmes** [comment]
Fixed in commit 146bf30.
