### ISSUE TITLE
.css needs to be converted to .scss

### ISSUE THREAD

**Issue by pszpak** [martindholmes/BreezeMap#19]
Make the .css into .scss.

**Comment by martindholmes** [comment]
I would git mv the current css file to an scss file. Once that's done on the issue 19 branch, let me know and I'll add a build step to rebuild so.

**Comment by martindholmes** [comment]
I'll take this ticket back and do it.

**Comment by martindholmes** [comment]
This is actually already done. The ticket was still open to allow @pszpak  to rework the SCSS per his preferences, but rather than leave it languishing, I'll close it and we can come to this work when there's a downstream project requirement for @pszpak to work on the project.
