### ISSUE TITLE
ant build process needs js engine

### ISSUE THREAD

**Issue by pszpak** [martindholmes/BreezeMap#23]
Build fails with this error:

  [get] To: /Users/pszpak/Documents/websites/BreezeMap/js/ol_latest.json
      [get] local file date : Wed Mar 31 11:33:45 PDT 2021
      [get] Not modified - so not downloaded
Java 15 has removed Nashorn, you must provide an engine for running JavaScript yourself. GraalVM JavaScript currently is the preferred option.

BUILD FAILED
/Users/pszpak/Documents/websites/BreezeMap/utilities/build.xml:202: The following error occurred while executing this line:
/Users/pszpak/Documents/websites/BreezeMap/utilities/build.xml:100: Unable to create javax script engine for javascript

**Comment by martindholmes** [comment]
Working on this in branch issue-23-ant-js. I think we can use XSLT instead of JS to parse the JSON release files.

**Comment by martindholmes** [comment]
Done. Thanks @pszpak.
