### ISSUE TITLE
Feature request: more control over timeline

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/BreezeMap#38]
Adding 'next' and 'previous' buttons would allow a gradual progression through the timeline at the user's leisure.

**Comment by martindholmes** [comment]
Working on this in issue-38-timeline.

**Comment by martindholmes** [comment]
Initial implementation has now been merged; will wait to test with various projects before closing.

**Comment by martindholmes** [comment]
Looks good on projects. Closing.
