### ISSUE TITLE
Feature request: custom icons

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/BreezeMap#39]
Allowing the use of custom icons for places would make the visual identification of places (or 'events' on the timeline) more intuitive. 
For example, a festival AND an oil spill in the same time period may appear on the map simultaneously. Using the standard 'location' icon for each requires the user to figure out the significance of each. Custom 'oil spill' and 'festival' icons would make clear the significance of each place.

**Comment by martindholmes** [comment]
This requires that images be specified in the XML somewhere, presumably in the categories -- or would you want to specify them in the actual places, so each place could have its own icon?

**Comment by gtnewton** [comment]
I think that assigning icons to categories makes the most sense. It keeps the page tidier and is relatively easy to assign while creating categories.

**Comment by martindholmes** [comment]
OK, in progress now...

**Comment by martindholmes** [comment]
This is now working, and there's an explanation of how to define the icon in the documentation.
