### ISSUE TITLE
Documentation typo(?)

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/BreezeMap#51]
To add a graphic (icon) the documentation example (section4.1) shows the graphic element as a descendant of an objectDesc element, but the Appendix A.1.21 documentation shows it as an objectType. This is reflected in the functioning campus map example.

Fix is to change section 4.1 in documentation to use objectType rather than objectDesc.

**Comment by martindholmes** [comment]
Fixed in commit 12be85d.
