### ISSUE TITLE
Move explicit style declarations (currently in JS) to CSS

### ISSUE THREAD

**Issue by gtnewton** [martindholmes/BreezeMap#53]
In the hol.VectorLayer.prototype.parseSearch function we have `this.docDisplayDiv.style.left = '-21rem';`
If this was part of a CSS class it could be easily changed by users. The JS would then be used to swap classes instead of editing explicit values in JS.

**Comment by martindholmes** [comment]
@gtnewton Fixed in commit [87a9a2a](https://github.com/martindholmes/BreezeMap/commit/87a9a2a58e42f459adfb0569db3b9b053a7c28ec). Closing this ticket.

**Comment by martindholmes** [comment]
@gtnewton To clarify: We now toggle a "hidden" class on the element to hide and show it. You can override the ruleset for that class.
